[package]
name = "blaze"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.10"
bson = "2.10"
ctrlc = "3.4.4"
rand = "0.8"
strum = "0.26"
colored = "2.1.0"
strum_macros = "0.26"
dotenvy = "0.15"
serde = { version = "1.0", features = ["derive"] }
