[package]
name = "blaze"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.10"
bson = "2.10"
rand = "0.8"
strum = "0.26"
strum_macros = "0.26"
dotenvy = "0.15"

[[bin]]
name = "blaze"
path = "src/main.rs"

[lib]
path = "src/lib.rs"
